### ISSUE TITLE
启动模拟后蓝牙无法打开，

### ISSUE THREAD

**Issue by mymine** [dreamncn/bluetooth#1]
MIUI14安卓13启动模拟后蓝牙无法打开，获取的Raw data数据不正确。
![Screenshot_2023-05-16-00-48-40-799_net ankio bluetooth](https://github.com/dreamncn/bluetooth/assets/2943365/4e0d3dca-5a27-4202-9a84-e30684416dca)
这是nRF Connect获取的Raw data正确数据
![Screenshot_2023-05-16-00-50-26-032_no nordicsemi android mcp](https://github.com/dreamncn/bluetooth/assets/2943365/0359c7ef-256a-4815-acd1-24e15d2078e3)

**Comment by dreamncn** [comment]
提供lsp日志

**Comment by dreamncn** [comment]
数据应该没什么问题的，这边测试过

**Comment by mymine** [comment]
> 提供lsp日志

[modules_2023-05-16T10:27:05.647116.log](https://github.com/dreamncn/bluetooth/files/11483429/modules_2023-05-16T10.27.05.647116.log)
#
[verbose_2023-05-16T10:27:07.204593.log](https://github.com/dreamncn/bluetooth/files/11483430/verbose_2023-05-16T10.27.07.204593.log)
[verbose_2023-05-16T10:27:10.042317.log](https://github.com/dreamncn/bluetooth/files/11483431/verbose_2023-05-16T10.27.10.042317.log)

**Comment by dreamncn** [comment]
> > 提供lsp日志
> 
> [modules_2023-05-16T10:27:05.647116.log](https://github.com/dreamncn/bluetooth/files/11483429/modules_2023-05-16T10.27.05.647116.log)
> 
> [verbose_2023-05-16T10:27:07.204593.log](https://github.com/dreamncn/bluetooth/files/11483430/verbose_2023-05-16T10.27.07.204593.log) [verbose_2023-05-16T10:27:10.042317.log](https://github.com/dreamncn/bluetooth/files/11483431/verbose_2023-05-16T10.27.10.042317.log)

不是数据的问题，是hook方法的问题
>  Crash unexpectedly: java.lang.NoSuchMethodError: com.android.bluetooth.gatt.GattService#onScanResult(java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,byte[],java.lang.String)

方便提取miui上的`com.android.bluetooth`文件给我吗？

**Comment by mymine** [comment]
> > > 提供lsp日志
> > 
> > 
> > [modules_2023-05-16T10:27:05.647116.log](https://github.com/dreamncn/bluetooth/files/11483429/modules_2023-05-16T10.27.05.647116.log)
> > [verbose_2023-05-16T10:27:07.204593.log](https://github.com/dreamncn/bluetooth/files/11483430/verbose_2023-05-16T10.27.07.204593.log) [verbose_2023-05-16T10:27:10.042317.log](https://github.com/dreamncn/bluetooth/files/11483431/verbose_2023-05-16T10.27.10.042317.log)
> 
> 不是数据的问题，是hook方法的问题
> 
> > Crash unexpectedly: java.lang.NoSuchMethodError: com.android.bluetooth.gatt.GattService#onScanResult(java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,byte[],java.lang.String)
> 
> 方便提取miui上的`com.android.bluetooth`文件给我吗？
https://lanzoui.com/iVJ1I0wartqf

**Comment by dreamncn** [comment]
已修复：https://github.com/dreamncn/bluetooth/releases/tag/1.0.3

**Comment by mymine** [comment]
> 已修复：https://github.com/dreamncn/bluetooth/releases/tag/1.0.3

OK

**Comment by mymine** [comment]
> 已修复：https://github.com/dreamncn/bluetooth/releases/tag/1.0.3

获取的raw data数据不对。nRF Connect获取的Raw data正确数据可以打卡

**Comment by dreamncn** [comment]
这个问题新开issue讨论 #2
