### ISSUE TITLE
这个可以支持LSPatch吗

### ISSUE THREAD

**Issue by C-loudplayer** [dreamncn/bluetooth#4]
这个可以支持LSPatch吗

**Comment by dreamncn** [comment]
没法支持的哈，hook的是系统应用

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："jiaminghai ***@***.***&gt;;
发送时间：2023年6月20日(星期二) 下午5:18
收件人："dreamncn/bluetooth" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[dreamncn/bluetooth] 这个可以支持LSPatch吗 (Issue #4)
-----------------------------------

 

 
这个可以支持LSPatch吗
